### ISSUE TITLE
plugin not found

### ISSUE THREAD

**Issue by alanmoment** [mderevyankoaqa/jmeter-influxdb-listener-plugin#3]
Hi, I'm use jmeter 5.3 and put plugin into lib/ext. But I can't found jmeter-influxdb-listener-plugin in the select option when I open the jmeter. what's going on?

**Comment by mderevyankoaqa** [comment]
hi @alanmoment, please try a clean installation - unzip JMeter and put plugin; the first thing. Any logs from JMeter? For direct support, try skype "michal_v_derevyanko". The plugin requires Java 11, make sure that you have it.

**Comment by mderevyankoaqa** [comment]
The next release will make the compatibility with java 1.8, so for now when java version is "1.8.0_221" - no plugin here as you reported, but for java version "13.0.2" 2020-01-14 - works well

**Comment by alanmoment** [comment]
Sorry, I’m not got your reply notice. Before days ago, I just saw load plugin  from log but nothing to happened.

My Java version is 1.8.0_202-ea

And very thanks you fix this problem! I’ll try it again.

**Comment by mderevyankoaqa** [comment]
@alanmoment to be clear, please just install java 11 or higher, the plugin should be available from JMeter UI and nongui mode. 
For java 1.8 the current version of the plugin will not work defiantly. Thank you.

**Comment by mderevyankoaqa** [comment]
Closed, infrastructure issue, lack of Java 11
